// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	//AddTime
	//
	//  INSERT INTO times (timespan, year, month, day_of_month) VALUES (?, ?, ?, ?)
	AddTime(ctx context.Context, timespan string, year int64, month int64, dayOfMonth int64) error
	//GetTimesYear
	//
	//  SELECT timespan FROM times WHERE year = ?
	GetTimesYear(ctx context.Context, year int64) ([]string, error)
	//GetTimesYearMonth
	//
	//  SELECT timespan FROM times WHERE year = ? AND month = ?
	GetTimesYearMonth(ctx context.Context, year int64, month int64) ([]string, error)
	//GetTimesYearMonthDay
	//
	//  SELECT timespan FROM times WHERE year = ? AND month = ? AND day_of_month = ?
	GetTimesYearMonthDay(ctx context.Context, year int64, month int64, dayOfMonth int64) ([]string, error)
}

var _ Querier = (*Queries)(nil)
